server:
  port: 8100

spring:
  application:
    name: CINEMA-API

  datasource:
    url: "jdbc:mysql://localhost:3306/cinema_booking_system" 
    username: root
    password: harshitsaxena

  jpa:
    properties:
      hibernate.jdbc.batch_size: 5
    
    show-sql: true

logging.level.org.springframework: trace

##eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka  --?