spring:
  application:
    name: CINEMA-API
  
  cloud:
    config:
      uri: http://localhost:8888

logging:
  level:
    org.springframework.security: TRACE

##eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka  --?