server:
  port: 8100

spring:
  application:
    name: CINEMA-API
  
  cloud:
    config:
      uri: http://localhost:8888

  jpa:
    properties:
      hibernate.jdbc.batch_size: 5
    
    show-sql: true

logging.level.org.springframework: trace

##eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka  --?